---
title: "Kilifi North"
---

There were two dispensaries in Kilifi North subcounty: Kiwandani and Kadzinuni.

```{r}
#| label: kn-map
#| echo: false
#| warning: false
#| results: hide

source("src/maps.R")

# plot
kn_hf
```

------------------------------------------------------------------------

## Malaria trends

::: panel-tabset
## Under 5

```{r}
#| label: kn-u5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

source("src/moh705.R")

plot_malaria_cases(moh705A_long %>% filter(subcounty == "Kilifi North"), 
                   "under-5 years")
```

## Over 5

```{r}
#| label: ganze-o5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

plot_malaria_cases(moh705B_long %>% filter(subcounty == "Kilifi North"), 
                   "over-5 years")

```
:::

------------------------------------------------------------------------

## Malaria treatment

::: panel-tabset
## Under 5

## Over 5

## Malaria in pregnancy
:::

------------------------------------------------------------------------

## Bednets

::: panel-tabset
## Access

## Use
:::

------------------------------------------------------------------------
