---
title: "Kilifi South"
---

## Study sites

There were two dispensaries in Kilifi South: Pingilikani and Tunzanani.

```{r}
#| label: ks-map
#| echo: false
#| warning: false
#| results: hide

source("src/functions.R")
source("src/maps.R")
source("src/chp_data.R")

# plot
ks_hf
```

------------------------------------------------------------------------

## Malaria trends per health facility

::: panel-tabset
## Under 5

```{r}
#| label: ganze-u5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

source("src/moh705.R")

plot_malaria_cases(moh705A_long %>% filter(subcounty == "Kilifi South"), 
                   "under-5 years")
```

## Over 5

```{r}
#| label: ganze-o5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

plot_malaria_cases(moh705B_long %>% filter(subcounty == "Kilifi South"), 
                   "over-5 years")
```
:::

------------------------------------------------------------------------

## Malaria treatment

::: panel-tabset
## Under 5

## Over 5

## Malaria in pregnancy
:::

------------------------------------------------------------------------

## Bednet ownership and usage

::: panel-tabset
## Net ownership

Proportion of people who owned a net over the study period.

```{r}
#| label: klfsouth-net-ownership
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 6

# plot fig
fig_have_net_klfsouth
```

## Net usage

Proportion of people who slept under a net the previous night over the study period.

```{r}
#| label: klfsouth-net-usage
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 6

fig_use_net_klfsouth
```
:::

------------------------------------------------------------------------
