---
title: "Rabai"
---

There were two dispensaries in Rabai subcounty: Lenga and Makanzani.

```{r}
#| label: rabai-map
#| echo: false
#| warning: false
#| results: hide

source("src/functions.R")
source("src/maps.R")
source("src/moh706.R")
source("src/chp_data.R")

# plot
rabai_hf
```

## Malaria trends per health facility

::: panel-tabset
## Under 5

```{r}
#| label: rabai-u5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

source("src/moh705.R")

plot_malaria_cases(moh705A_long %>% filter(subcounty == "Rabai"), 
                   "under-5 years")
```

## Over 5

```{r}
#| label: rabai-o5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

plot_malaria_cases(moh705B_long %>% filter(subcounty == "Rabai"), "over-5 years")

```
:::

------------------------------------------------------------------------



## Malaria testing
Total number of tests done and number positive by type (Microscopy and Rapid Diagnostic Testing (RDT))

::: panel-tabset
## Microscopy blood smear <5 years
```{r}
#| label: mbs-u5-ks
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

# plot figure
plot_malaria_test_type(moh706_dispensary_quarters |> filter(subcounty == "Rabai"), 
                       "mbs_u5", "Microscopy", "<5 years", "dispensary")
```

## Microscopy blood smear ≥5 years

```{r}
#| label: mbs-o5-ks
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

# plot figure
plot_malaria_test_type(moh706_dispensary_quarters |> filter(subcounty == "Rabai"), 
                       "mbs_o5", "Microscopy", "≥5 years", "dispensary")
```

## RDT <5 years
```{r}
#| label: rdt-o5-ks
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

# plot figure
plot_malaria_test_type(moh706_dispensary_quarters |> filter(subcounty == "Rabai"), 
                       "mrdt_u5", "RDT", "<5 years", "dispensary")
```

## RDT ≥5 years
```{r}
#| label: mrdt-o5-ks
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 5

# plot figure
plot_malaria_test_type(moh706_dispensary_quarters |> filter(subcounty == "Rabai"), 
                       "mrdt_o5", "RDT", "≥5 years", "dispensary")
```

:::

------------------------------------------------------------------------


## Malaria treatment

::: panel-tabset
## Under 5

## Over 5

## Malaria in pregnancy
:::

------------------------------------------------------------------------

## Bednet ownership and usage

::: panel-tabset
## Net ownership

Proportion of people who owned a net over the study period.

```{r}
#| label: rabai-net-ownership
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 6

# plot fig
fig_have_net_rabai
```

## Net usage

Proportion of people who slept under a net the previous night over the study period.

```{r}
#| label: rabai-net-usage
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 6

fig_use_net_rabai
```
:::

------------------------------------------------------------------------
