---
title: "Overview of indicators"
---

```{r}
#| label: generate-indicators
#| echo: false
#| warning: false

source("src/functions.R")
source("src/moh705.R")
source("src/chp_data.R")
```

## Reporting rates

::: panel-tabset
## MOH 515

## MOH 705A

## MOH 705B
:::

------------------------------------------------------------------------

## Malaria trends

::: panel-tabset
## Under 5

Total number of [**suspected**]{style="color:#bdbdbd"}, [**tested**]{style="color:#7570b3"}, and [**confirmed**]{style="color:#d95f02"} malaria cases by sub-county.

```{r}
#| label: generate-indicators-u5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 15

fig3_moh705A
```

## Over 5

Total number of [**suspected**]{style="color:#bdbdbd"}, [**tested**]{style="color:#7570b3"}, and [**confirmed**]{style="color:#d95f02"} malaria cases by sub-county.

```{r}
#| label: generate-indicators-o5
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 15

# plot figure
fig5_moh705B

```
:::

------------------------------------------------------------------------

## Bednet ownership and usage

::: panel-tabset
## Net ownership

Proportion of people who owned a net over the study period.

```{r}
#| label: generate-indicators-net-ownership
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 6

# plot fig
fig_own_net_subcounty

```

## Net usage

Proportion of people who slept under a net the previous night over the study period.

```{r}
#| label: generate-indicators-net-usage
#| echo: false
#| warning: false
#| fig-width: 12
#| fig-height: 6

fig_use_net_subcounty
```
:::
